openapi: 3.0.3
info:
  title: Stock Unit API
  version: 1.0.0
  description: Stock Unit API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: http://localhost:1323
paths:
  /stock/units:
    post:
      tags: ["Stock Unit"]
      summary: Create Stock Unit
      description: Create Stock Unit
      operationId: PostStockUnit
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewStockUnit"
      responses:
        "201":
          $ref: "#/components/responses/Created"
        "400":
          $ref: "#/components/responses/BadRequest"
        "500":
          $ref: "#/components/responses/InternalServerError"
  /stock/units/{stockUnitId}:
    put:
      tags: ["Stock Unit"]
      summary: Update Stock Unit
      description: Update Stock Unit
      operationId: PutStockUnit
      parameters:
        - in: path
          name: stockUnitId
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewStockUnit"
      responses:
        "200":
          $ref: "#/components/responses/OK"
        "400":
          $ref: "#/components/responses/BadRequest"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/InternalServerError"
    delete:
      tags: ["Stock Unit"]
      summary: Delete Stock Unit
      description: Delete Stock Unit
      operationId: DeleteStockUnit
      parameters:
        - in: path
          name: stockUnitId
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          $ref: "#/components/responses/OK"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/InternalServerError"

components:
  responses:
    Created:
      description: Created
      content:
        application/json:
          schema:
            required:
              - id
            properties:
              id:
                type: string
                format: uuid
                x-oapi-codegen-extra-tags:
                  validate: required
    OK:
      description: OK
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/BadRequestResponse"
    NotFound:
      description: Not Found
    InternalServerError:
      description: Internal Server Error
  schemas:
    BadRequestResponse:
      required:
        - message
      properties:
        message:
          type: string
    NewStockUnit:
      required:
        - items
        - location
      type: object
      properties:
        items:
          type: array
          items:
            type: string
            format: uuid
        location:
          type: string


