// Package unit provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.0.0 DO NOT EDIT.
package unit

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// BadRequestResponse defines model for BadRequestResponse.
type BadRequestResponse struct {
	Message string `json:"message"`
}

// NewStockUnit defines model for NewStockUnit.
type NewStockUnit struct {
	Items    []openapi_types.UUID `json:"items"`
	Location string               `json:"location"`
}

// BadRequest defines model for BadRequest.
type BadRequest = BadRequestResponse

// Created defines model for Created.
type Created struct {
	Id openapi_types.UUID `json:"id" validate:"required"`
}

// PostStockUnitJSONRequestBody defines body for PostStockUnit for application/json ContentType.
type PostStockUnitJSONRequestBody = NewStockUnit

// PutStockUnitJSONRequestBody defines body for PutStockUnit for application/json ContentType.
type PutStockUnitJSONRequestBody = NewStockUnit
